default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: ENV["SCHEME_NAME"],
      project: "./BeforeGoing.xcodeproj",
      destination: 'platform=iOS Simulator,name=iPhone 16',
      derived_data_path: "DerivedData",
      result_bundle: true,
      code_coverage: true,
      output_directory: ".",
      output_types: "junit,xcresult"
    )
  end
end